[package]
name = "esp-trace-decoder"
version = "0.1.0"
edition = "2021"

[lib]
name = "tracedecode"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
pretty_env_logger = "0.5.0"

log = "0.4.20"
object = "0.32.1"
